### ISSUE TITLE
Moteur Velux IO

### ISSUE THREAD

**Issue by Xavier-M** [echauvet/freebox_home#2]
Bonjour,

Tout d'abord merci pour votre travail que j'ai testé hier et qui marche super pour commander un volet Velux IO HomeControl par la Freebox.

J'ai également un Velux motorisé, qui est bien géré par l'application Freebox Home mais qui n'apparaît pas avec cette intégration. Est-ce que ce vous intéresse d'ajouter ce support ? Je ne sais pas si c'est simple ou non.
Je peux faire des tests ou des manipulations si ça peut aider.

Dans le code j'ai vu qu'il y a un filtre sur shutter ou basic_shutter, j'imagine que la fenêtre doit avoir un autre type.

Merci

**Comment by Xavier-M** [comment]
J'ai fait un test ici : https://github.com/Xavier-M/freebox_home/tree/velux et ça marche :)

Le code pour "shutter" marche parfaitement, il faut juste accepter la category "opener" renvoyé par l'API freebox.

**Comment by sgouedj** [comment]
Bonjour,
J ai procédé a l'intégration, j obtiens bien les entités de la delta (disk, détecteur, caméra, télécommande...), mais je ne vois pas mes volets rts connectés à la delta.
Y a t'il une manipulation à faire ?
Cordialement

**Comment by echauvet** [comment]
> J'ai fait un test ici : https://github.com/Xavier-M/freebox_home/tree/velux et ça marche :)
> 
> Le code pour "shutter" marche parfaitement, il faut juste accepter la category "opener" renvoyée par l'API freebox.

Merci, les changements sont reportés.
